# Generated by Django 2.2 on 2020-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_style',
            field=models.CharField(blank=True, default='单词', max_length=20, null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='语言考试类别'),
        ),
    ]
