# Generated by Django 2.2 on 2020-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20200408_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='产品名'),
        ),
    ]
