# Generated by Django 2.2 on 2020-04-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, verbose_name='创建日期')),
                ('title', models.CharField(default='0', max_length=30, verbose_name='订单号')),
                ('content', models.CharField(default='0', max_length=200, verbose_name='订单号')),
            ],
        ),
        migrations.CreateModel(
            name='Commends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, verbose_name='评论日期')),
                ('username', models.CharField(default='0', max_length=20, verbose_name='用户名')),
                ('content', models.CharField(default='0', max_length=30, verbose_name='评论内容')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Pages')),
                ('recommend', models.ManyToManyField(to='Forum.Commends')),
            ],
        ),
    ]
