# Generated by Django 2.2 on 2020-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20200404_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(default='0', max_length=2000, verbose_name='订单号'),
        ),
    ]
