# Generated by Django 2.2 on 2020-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20200404_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='username',
            field=models.CharField(default='0', max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(default='', max_length=2000, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='订单号'),
        ),
    ]
