# Generated by Django 2.2 on 2020-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_auto_20200404_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='pages',
            name='views',
            field=models.IntegerField(default=0, verbose_name='观看数'),
        ),
    ]
