# Generated by Django 2.2 on 2020-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_auto_20200404_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='last_view',
            field=models.DateField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='Date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
