# Generated by Django 2.2 on 2020-04-04 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0009_auto_20200404_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='like_person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(default='', max_length=2000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
        ),
    ]
