# Generated by Django 2.2 on 2020-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0010_auto_20200405_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='like_down',
            field=models.IntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AddField(
            model_name='pages',
            name='like_up',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
