# Generated by Django 2.2 on 2020-04-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0012_auto_20200405_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commends',
            name='recommend',
        ),
    ]
