# Generated by Django 2.2 on 2020-04-06 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0013_remove_commends_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opertaion', models.BooleanField(null=True, verbose_name='点赞 or 踩')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commends',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='commends',
            name='thumbs_up',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='like_down',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='like_up',
        ),
        migrations.AlterField(
            model_name='pages',
            name='like_person',
            field=models.ManyToManyField(to='Forum.likes'),
        ),
        migrations.AddField(
            model_name='commends',
            name='like_person',
            field=models.ManyToManyField(to='Forum.likes'),
        ),
    ]
