# Generated by Django 2.2 on 2020-04-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0014_auto_20200406_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='commends',
            name='like_down',
            field=models.IntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AddField(
            model_name='commends',
            name='like_up',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
