# Generated by Django 2.2 on 2020-04-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0015_auto_20200406_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commends',
            name='like_person',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='like_person',
        ),
        migrations.AddField(
            model_name='likes',
            name='commend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Commends'),
        ),
        migrations.AddField(
            model_name='likes',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Pages'),
        ),
    ]
