# Generated by Django 2.2 on 2020-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0016_auto_20200406_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='opertaion',
            field=models.IntegerField(null=True, verbose_name='点赞 or 踩'),
        ),
    ]
