# Generated by Django 2.2 on 2020-04-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0018_auto_20200406_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='comment_num',
        ),
    ]
