# Generated by Django 2.2 on 2020-04-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0019_remove_pages_comment_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='opertaion',
            new_name='operation',
        ),
    ]
