# Generated by Django 2.2 on 2020-03-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200330_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tasklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.taskList'),
        ),
    ]
