# Generated by Django 2.2 on 2020-03-30 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tasklist_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='产品名')),
                ('product_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='产品价格')),
                ('product_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品说明')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.DeleteModel(
            name='checkList',
        ),
        migrations.RemoveField(
            model_name='boughtproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='boughtproduct',
            name='username',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='username',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='traderecord',
            name='Sum',
        ),
        migrations.RemoveField(
            model_name='traderecord',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tasklist',
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='买商品的时间'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='quantity',
            field=models.IntegerField(default=0, max_length=15, verbose_name='产品数量'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='添加产品进购物车时间'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='quantity',
            field=models.IntegerField(default=0, max_length=15, verbose_name='产品数量'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='para',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.Parameter'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=0, max_length=15, verbose_name='产品数量'),
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Task'),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(to='users.product'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='product',
            field=models.ManyToManyField(to='users.product'),
        ),
    ]
