# Generated by Django 2.2 on 2020-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200330_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='产品数量'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='产品数量'),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='产品数量'),
        ),
    ]
