# Generated by Django 2.2 on 2020-03-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200330_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(to='myadmin.product'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.Task'),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='product',
            field=models.ManyToManyField(to='myadmin.product'),
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
