# Generated by Django 2.2 on 2020-03-30 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200330_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='para',
        ),
        migrations.AddField(
            model_name='parameter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
