# Generated by Django 2.2 on 2020-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='traderecord',
            name='quantity',
        ),
        migrations.AddField(
            model_name='traderecord',
            name='Total',
            field=models.CharField(default='0', max_length=10, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='recordId',
            field=models.CharField(default='0', max_length=20, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='url',
            field=models.CharField(default='0', max_length=20, verbose_name='url'),
        ),
    ]
