# Generated by Django 2.2 on 2020-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200402_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='desc',
            field=models.CharField(default='0', max_length=20, verbose_name='描述'),
        ),
    ]
