# Generated by Django 2.2 on 2020-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_traderecord_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderecord',
            name='url',
            field=models.CharField(default='0', max_length=50, verbose_name='url'),
        ),
    ]
