# Generated by Django 2.2 on 2020-04-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200402_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderecord',
            name='url',
        ),
    ]
