# Generated by Django 2.2 on 2020-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_traderecord_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='status',
            field=models.CharField(default='正在支付', max_length=10, verbose_name='状态'),
        ),
    ]
