# Generated by Django 2.2 on 2020-04-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_traderecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
