# Generated by Django 2.2 on 2020-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0010_auto_20200405_0106'),
        ('users', '0016_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='like',
            field=models.ManyToManyField(to='Forum.Pages'),
        ),
    ]
