# Generated by Django 2.2 on 2020-04-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200409_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtproduct',
            name='quantity',
        ),
    ]
