# Generated by Django 2.2 on 2020-04-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_parameter_selected_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='selected_words',
        ),
    ]
