# Generated by Django 2.2 on 2020-04-10 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0003_auto_20200408_1100'),
        ('users', '0022_remove_parameter_selected_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='word_forget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, verbose_name='购买日期')),
                ('count', models.IntegerField(default=0, verbose_name='错误单词次数')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsys.words', verbose_name='错误的单词')),
            ],
        ),
    ]
