# Generated by Django 2.2 on 2020-04-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_word_forget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_forget',
            name='count',
            field=models.IntegerField(default=1, verbose_name='错误单词次数'),
        ),
    ]
