# Generated by Django 2.2 on 2020-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_product_task'),
        ('mainsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='product',
        ),
        migrations.AddField(
            model_name='words',
            name='product',
            field=models.ManyToManyField(null=True, to='myadmin.product'),
        ),
    ]
