# Generated by Django 2.2 on 2020-04-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0002_auto_20200407_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='product',
            field=models.ManyToManyField(to='myadmin.product'),
        ),
    ]
