# Generated by Django 2.2 on 2020-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20200409_0049'),
        ('mainsys', '0003_auto_20200408_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='writes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='无标题', max_length=200, verbose_name='标题')),
                ('time', models.IntegerField(default=0, verbose_name='限制时间')),
                ('problem', models.CharField(default='', max_length=2000, verbose_name='问题')),
                ('top', models.CharField(default='', max_length=300, verbose_name='规范')),
                ('product', models.ManyToManyField(to='myadmin.product')),
            ],
        ),
    ]
