# Generated by Django 2.2 on 2020-04-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20200409_0049'),
        ('mainsys', '0004_writes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writes',
            name='product',
        ),
        migrations.AddField(
            model_name='writes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.product'),
        ),
    ]
