# Generated by Django 2.2 on 2020-04-13 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsys', '0005_auto_20200412_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='write_saving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='内容')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsys.writes')),
            ],
        ),
    ]
