# Generated by Django 2.2 on 2020-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0007_auto_20200413_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='read_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('mp3_url', models.CharField(default='', max_length=300, verbose_name='内容')),
                ('eng', models.CharField(default='', max_length=2000, verbose_name='英文内容')),
                ('chinese', models.CharField(default='', max_length=2000, verbose_name='中文内容')),
                ('title', models.CharField(default='', max_length=300, verbose_name='标题')),
            ],
        ),
    ]
