# Generated by Django 2.2 on 2020-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0008_read_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='read_data',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='read_data',
            name='mp3_url',
            field=models.CharField(default='', max_length=300, verbose_name='mp3内容'),
        ),
    ]
