# Generated by Django 2.2 on 2020-04-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0009_auto_20200414_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_data',
            name='mp3_url',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='mp3内容'),
        ),
    ]
