# Generated by Django 2.2 on 2020-04-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0010_auto_20200414_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_data',
            name='chinese',
            field=models.CharField(default='', max_length=3000, verbose_name='中文内容'),
        ),
        migrations.AlterField(
            model_name='read_data',
            name='eng',
            field=models.CharField(default='', max_length=3000, verbose_name='英文内容'),
        ),
    ]
