# Generated by Django 2.2 on 2020-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0011_auto_20200414_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='listen_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('mp3_url', models.CharField(default='', max_length=300, null=True, verbose_name='mp3内容')),
                ('eng', models.CharField(default='', max_length=3000, verbose_name='英文内容')),
                ('chinese', models.CharField(default='', max_length=3000, verbose_name='中文内容')),
                ('title', models.CharField(default='', max_length=300, verbose_name='标题')),
                ('url', models.CharField(default='', max_length=300, verbose_name='地址')),
                ('data_time', models.CharField(default='', max_length=1000, verbose_name='地址')),
            ],
        ),
    ]
