# Generated by Django 2.2 on 2020-04-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0012_listen_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_data',
            name='chinese',
            field=models.CharField(default='', max_length=4000, verbose_name='中文内容'),
        ),
    ]
