# Generated by Django 2.2 on 2020-04-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0014_auto_20200416_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen_data',
            name='eng',
            field=models.CharField(default='', max_length=5000, verbose_name='英文内容'),
        ),
    ]
