# Generated by Django 2.2 on 2020-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0015_auto_20200416_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listen_data',
            name='eng',
            field=models.CharField(default='', max_length=5500, verbose_name='英文内容'),
        ),
    ]
