# Generated by Django 2.2 on 2020-04-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0016_auto_20200416_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_data',
            name='chinese',
            field=models.CharField(default='', max_length=5000, verbose_name='中文内容'),
        ),
    ]
